name: Setup
description: Download and install 3rd party software.
runs:
  using: composite
  steps:
    - name: Install Mise
      uses: jdx/mise-action@v3.5.0
      with:
        version: 2025.11.3

    - name: Install Dependencies
      shell: bash
      run: pnpm i --frozen-lockfile

    - name: Configure Git
      shell: bash
      run: |
        git config --global init.defaultBranch main
        git config --global user.email "you@example.com"
        git config --global user.name "Your Name"
