# This file describes a Fastly Compute@Edge package. To learn more visit:
# https://developer.fastly.com/reference/fastly-toml/

name = "Tempest"
authors = [""]
description = ""
language = "javascript"
manifest_version = 2
service_id = ""

[scripts]
  build = "bun build ./src/index.tsx --outdir ./bin --external fastly:* && js-compute-runtime bin/index.js bin/main.wasm"
