yarnPath: .yarn/releases/yarn-3.6.1.cjs
nodeLinker: pnp
pnpMode: "loose"

packageExtensions:
    "@types/node@*":
        dependencies:
            "events": "*"
    "@types/npmlog@*":
        dependencies:
            "events": "*"
    "@types/react@*":
        dependencies:
            "prop-types": "*"
            "scheduler": "*"
    "@types/react-dom@*":
        dependencies:
            "react": "*"
    "@vitest/expect@*":
        dependencies:
            "@types/chai": "*"
    "debug@*": 
        dependencies:
            "supports-color": "*"
    "dotenv@*":
        dependencies:
            "@types/node": "*"
    "engine.io@*":
        dependencies:
            "events": "*"
    "happy-dom@*":
        dependencies:
            "@types/node": "*"
    "json-schema-to-zod@*":
        dependencies:
            "json-schema": "*"
    "local-pkg@*": 
        dependencies:
            "happy-dom": "*"
            "jsdom": "*"
    "recoil@*":
        dependencies:
            "@types/react": "*"
    "simple-git@*":
        dependencies:
            "@types/node": "*"
    "socket.io@*":
        dependencies:
            "@types/node": "*"
            "events": "*"
    "socket.io-adapter@*":
        dependencies:
            "@types/node": "*"
            "events": "*"
    "@svgr/core@*":
        dependencies:
            "prettier": "*"
    "@svgr/babel-plugin-transform-svg-component@*":
        dependencies:
            "@babel/template": "*"
    "vite@*": 
        dependencies:
            "happy-dom": "*"
            "supports-color": "*"
    "vitest@*": 
        dependencies:
            "jsdom": "*"
    "vite-plugin-svgr@*":
        dependencies:
            "@types/react": "*"
            "react": "*"
