// @ts-check
import eslint from "eslint"
import parser from "@typescript-eslint/parser"
import plugin from "@typescript-eslint/eslint-plugin"

/** @type {import("@typescript-eslint/parser").ParserOptions} */
const parserOptions = {
  project: [
    `./tsconfig.json`, 
    `./tsconfig.config.json`, 
    `./apps/web/smithy/tsconfig.json`, 
    `./packages/atom.io/tsconfig.json`
  ],
  sourceType: `module`
}

/** @type {import("eslint").Linter.FlatConfig} */
const config = {
  languageOptions: {
    parser,
		// @ts-expect-error these parser options are valid
    parserOptions
  },
  files: [`**/*.ts{,x}`, `eslint.config.js`],
  ignores: [`**/dist/**/*`, `**/projects/**/*`, `**/*.schema.json.ts`],
	// @ts-expect-error this plugin is valid
  plugins: { "@typescript-eslint": plugin },
  rules: {
    "@typescript-eslint/adjacent-overload-signatures": 2,
    "@typescript-eslint/array-type": 0,
    "@typescript-eslint/await-thenable": 0,
    "@typescript-eslint/ban-ts-comment": 2,
    "@typescript-eslint/ban-tslint-comment": 0,
    "@typescript-eslint/ban-types": 2,
    "@typescript-eslint/class-literal-property-style": 2,
    "@typescript-eslint/consistent-generic-constructors": 0,
    "@typescript-eslint/consistent-indexed-object-style": 0,
    "@typescript-eslint/consistent-return": 0,
    "@typescript-eslint/consistent-type-assertions": 0,
    "@typescript-eslint/consistent-type-definitions": 0,
    "@typescript-eslint/consistent-type-exports": 2,
    "@typescript-eslint/consistent-type-imports": [
      2,
      {
        fixStyle: `separate-type-imports`,
        prefer: `type-imports`, 
      },
    ],
    "@typescript-eslint/default-param-last": 2,
    "@typescript-eslint/dot-notation": 0,
    "@typescript-eslint/explicit-function-return-type": 0,
    "@typescript-eslint/explicit-member-accessibility": 2,
    "@typescript-eslint/explicit-module-boundary-types": 2,
    "@typescript-eslint/init-declarations": 0,
    "@typescript-eslint/max-params": 0,
    "@typescript-eslint/member-ordering": 0,
    "@typescript-eslint/method-signature-style": 0,
    "@typescript-eslint/naming-convention": [
      2,
      {
        selector: `variable`,
        format: [`camelCase`, `PascalCase`, `UPPER_CASE`],
        leadingUnderscore: `allow`,
        trailingUnderscore: `allow`,
      },
    ],
    "@typescript-eslint/no-array-constructor": 2,
    "@typescript-eslint/no-array-delete": 2,
    "@typescript-eslint/no-base-to-string": 2,
    "@typescript-eslint/no-confusing-non-null-assertion": 2,
    "@typescript-eslint/no-confusing-void-expression": 2,
    "@typescript-eslint/no-duplicate-enum-values": 2,
    "@typescript-eslint/no-duplicate-type-constituents": 2,
    "@typescript-eslint/no-dynamic-delete": 2,
    "@typescript-eslint/no-empty-function": 0,
    "@typescript-eslint/no-empty-interface": 2,
    "@typescript-eslint/no-explicit-any": 0,
    "@typescript-eslint/no-extra-non-null-assertion": 2,
    "@typescript-eslint/no-extraneous-class": 0,
    "@typescript-eslint/no-floating-promises": 2,
    "@typescript-eslint/no-for-in-array": 2,
    "@typescript-eslint/no-implied-eval": 2,
    "@typescript-eslint/no-import-type-side-effects": 2,
    "@typescript-eslint/no-inferrable-types": 2,
    "@typescript-eslint/no-invalid-void-type": 0,
    "@typescript-eslint/no-loop-func": 0,
    "@typescript-eslint/no-loss-of-precision": 2,
    "@typescript-eslint/no-magic-numbers": 0,
    "@typescript-eslint/no-meaningless-void-operator": 2,
    "@typescript-eslint/no-misused-new": 2,
    "@typescript-eslint/no-misused-promises": 0,
    "@typescript-eslint/no-mixed-enums": 2,
    "@typescript-eslint/no-namespace": 2,
    "@typescript-eslint/no-non-null-asserted-nullish-coalescing": 2,
    "@typescript-eslint/no-non-null-asserted-optional-chain": 2,
    "@typescript-eslint/no-non-null-assertion": 0,
    "@typescript-eslint/no-redundant-type-constituents": 2,
    "@typescript-eslint/no-require-imports": 2,
    "@typescript-eslint/no-restricted-imports": 0,
    "@typescript-eslint/no-shadow": 2,
    "@typescript-eslint/no-this-alias": 2,
    "@typescript-eslint/no-throw-literal": 2,
    "@typescript-eslint/no-unnecessary-boolean-literal-compare": 0,
    "@typescript-eslint/no-unnecessary-condition": 0,
    "@typescript-eslint/no-unnecessary-qualifier": 0,
    "@typescript-eslint/no-unnecessary-type-arguments": 0,
    "@typescript-eslint/no-unnecessary-type-assertion": 2,
    "@typescript-eslint/no-unnecessary-type-constraint": 2,
    "@typescript-eslint/no-unsafe-argument": 0,
    "@typescript-eslint/no-unsafe-assignment": 0,
    "@typescript-eslint/no-unsafe-call": 0,
    "@typescript-eslint/no-unsafe-member-access": 0,
    "@typescript-eslint/no-unsafe-return": 0,
    "@typescript-eslint/no-unsafe-unary-minus": 2,
    "@typescript-eslint/no-unused-expressions": 0,
    "@typescript-eslint/no-unused-vars": 0,
    "@typescript-eslint/no-use-before-define": 0,
    "@typescript-eslint/no-useless-constructor": 2,
    "@typescript-eslint/no-useless-empty-export": 2,
    "@typescript-eslint/no-useless-template-literals": 2,
    "@typescript-eslint/no-var-requires": 2,
    "@typescript-eslint/non-nullable-type-assertion-style": 0,
    "@typescript-eslint/parameter-properties": 0,
    "@typescript-eslint/prefer-as-const": 2,
    "@typescript-eslint/prefer-destructuring": 0,
    "@typescript-eslint/prefer-enum-initializers": 2,
    "@typescript-eslint/prefer-find": 2,
    "@typescript-eslint/prefer-for-of": 2,
    "@typescript-eslint/prefer-function-type": 2,
    "@typescript-eslint/prefer-includes": 2,
    "@typescript-eslint/prefer-literal-enum-member": 2,
    "@typescript-eslint/prefer-namespace-keyword": 2,
    "@typescript-eslint/prefer-nullish-coalescing": 2,
    "@typescript-eslint/prefer-optional-chain": 2,
    "@typescript-eslint/prefer-promise-reject-errors": 2,
    "@typescript-eslint/prefer-readonly": 0,
    "@typescript-eslint/prefer-readonly-parameter-types": 0,
    "@typescript-eslint/prefer-reduce-type-parameter": 0,
    "@typescript-eslint/prefer-regexp-exec": 0,
    "@typescript-eslint/prefer-return-this-type": 2,
    "@typescript-eslint/prefer-string-starts-ends-with": 2,
    "@typescript-eslint/prefer-ts-expect-error": 2,
    "@typescript-eslint/promise-function-async": 0,
    "@typescript-eslint/require-array-sort-compare": 0,
    "@typescript-eslint/require-await": 2,
    "@typescript-eslint/restrict-plus-operands": 2,
    "@typescript-eslint/restrict-template-expressions": 2,
    "@typescript-eslint/return-await": 2,
    "@typescript-eslint/sort-type-constituents": 2,
    "@typescript-eslint/strict-boolean-expressions": 2,
    "@typescript-eslint/switch-exhaustiveness-check": 0,
    "@typescript-eslint/triple-slash-reference": 2,
    "@typescript-eslint/typedef": 0,
    "@typescript-eslint/unbound-method": 0,
    "@typescript-eslint/unified-signatures": 2,

    "no-mixed-spaces-and-tabs": `off`,
    "quotes": [2, `backtick`],
    "quote-props": [2, `consistent`, { unnecessary: false }],
  }
}
export default [config]

