[phases.setup]
nixPkgs = ['bun']
aptPkgs = ['unzip']

[phases.install]
cmds = ['bun upgrade', 'bun i']

[phases.build]
cmds = ['cd apps/core.wayfarer.quest && bun run build']

[start]
cmd = 'cd apps/core.wayfarer.quest && bun run start'