[phases.setup]
nixPkgs = ['bun']

[phases.install]
cmds = ['bun i']

[phases.build]
cmds = ['cd apps/core.wayfarer.quest', 'bun run build']

[start]
cmds = ['cd apps/core.wayfarer.quest', 'bun run start']