[phases.setup]
nixPkgs = ['bun', 'nodejs_22', 'pnpm',]
aptPkgs = ['unzip']

[phases.install]
cmds = ['bun upgrade', 'pnpm i']

[phases.build]
cmds = ['cd apps/core.wayfarer.quest && bun run build']

[start]
cmd = 'cd apps/core.wayfarer.quest && bun run start'