blockExoticSubdeps: true
minimumReleaseAge: 1440
minimumReleaseAgeExclude: []
autoInstallPeers: false

packages:
  - "apps/*"
  - "packages/*"
  - "templates/*"

allowBuilds:
  "@biomejs/biome": true
  "@parcel/watcher": true
  "@swc/core": true
  "@vercel/speed-insights": true
  "bun": true
  "esbuild": true
  "rolldown": true
  "sharp": true
  "unrs-resolver": true
  "workerd": true
