blockExoticSubdeps: true
minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - rolldown-plugin-dts@0.27.4
  - typescript@7.0.2
  - "@typescript/*"
autoInstallPeers: false
verifyDepsBeforeRun: error

overrides:
  rolldown-plugin-dts: 0.27.9

packages:
  - "apps/*"
  - "packages/*"

allowBuilds:
  "@swc/core": true
  dprint: true
  "esbuild": true
  "rolldown": true
  "sharp": true
  "unrs-resolver": true
  "workerd": true

peerDependencyRules:
  allowedVersions:
    typescript: ^5.0.0 || ^6.0.0 || ^7.0.0
