packages:
  - "apps/web/*"
  - "apps/node/*"
  - "apps/atom.io.fyi"
  - "apps/wayfarer.quest"
  - "packages/*"
  - "packages/@banka/*"
  - "packages/@banka/eslint-config/react"
  - "packages/@banka/eslint-config/rome"
  - "lib"
