packages:
  - "apps/*"
  - "apps/edge/*"
  - "apps/node/*"
  - "apps/web/*"
  - "packages/*"
  - "packages/create-atom.io/templates/*"
  - "templates/*"
onlyBuiltDependencies:
  - "@biomejs/biome"
  - "@parcel/watcher"
  - "@swc/core"
  - "@vercel/speed-insights"
  - "bun"
  - "esbuild"
  - "rolldown"
  - "sharp"
  - "unrs-resolver"
  - "workerd"
