blockExoticSubdeps: true
minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - "@typescript/*"
autoInstallPeers: false

packages:
  - "apps/*"
  - "packages/*"
  - "templates/*"

allowBuilds:
  "@swc/core": true
  dprint: true
  "esbuild": true
  "rolldown": true
  "sharp": true
  "unrs-resolver": true
  "workerd": true
