// Generate the upstream Cobra shell adapters and a protocol oracle for tests.
package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func main() {
	root := &cobra.Command{Use: "comline-template"}
	if len(os.Args) > 1 {
		root.ValidArgsFunction = func(cmd *cobra.Command, args []string, prefix string) ([]string, cobra.ShellCompDirective) {
			return []string{"closed\tClosed pull requests"}, cobra.ShellCompDirectiveNoFileComp
		}
		root.Flags().String("state", "", "PR state")
		root.RegisterFlagCompletionFunc("state", func(cmd *cobra.Command, args []string, prefix string) ([]string, cobra.ShellCompDirective) {
			return []string{"closed"}, cobra.ShellCompDirectiveNoFileComp
		})
		args := os.Args[1:]
		if args[0] == "oracle" {
			args = args[1:]
		}
		root.SetArgs(args)
		if err := root.Execute(); err != nil {
			panic(err)
		}
		return
	}
	scripts := map[string]string{}
	for _, shell := range []string{"bash", "zsh", "fish"} {
		var output bytes.Buffer
		var err error
		switch shell {
		case "bash":
			err = root.GenBashCompletionV2(&output, true)
		case "zsh":
			err = root.GenZshCompletion(&output)
		case "fish":
			err = root.GenFishCompletion(&output, true)
		}
		if err != nil {
			panic(err)
		}
		scripts[shell] = output.String()
	}
	content, err := json.Marshal(scripts)
	if err != nil {
		panic(err)
	}
	fmt.Println("// Generated by scripts/completions/main.go using Cobra v1.9.1 (Apache-2.0).")
	fmt.Println("// Regenerate: cd scripts/completions && go run . > ../../src/completion-scripts.gen.ts")
	fmt.Println("// See LICENSE.cobra. Do not edit by hand.")
	fmt.Println("// eslint-disable-next-line quotes")
	fmt.Printf("export const cobraScripts: { bash: string; zsh: string; fish: string } = %s\n", content)
}
