name: Setup

on:
  workflow_call:

defaults:
  run:
    shell: bash

jobs:
  Install:
    runs-on: ubuntu-latest
    timeout-minutes: 9
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 2

      - name: Set up pnpm
        uses: pnpm/action-setup@v4.0.0

      - name: Set up Node
        uses: actions/setup-node@v4.1.0
        with:
          node-version-file: .node-version
          cache: pnpm

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2.0.1
        with:
          bun-version-file: .bun-version

      - name: Install Dependencies
        run: pnpm i
