name: Test

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  TURBO_API: ${{ secrets.TURBO_API }}
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAMID: ${{ vars.TURBO_TEAMID }}

defaults:
  run:
    shell: bash

jobs:
  Vitest:
    runs-on: ubuntu-latest
    timeout-minutes: 9
    services:
      postgres:
        image: postgres:18.4-alpine3.23
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: your_password
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready --health-interval 1s --health-timeout 0.5s --health-retries 30
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: ./.github/actions/setup
      - run: pnpm run test
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        if: ${{ !cancelled() }}
        with:
          name: Varmint
          path: /tmp/varmint-uploads
          retention-days: 1

  Build:
    runs-on: ubuntu-latest
    timeout-minutes: 9
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: ./.github/actions/setup
      - run: pnpm run build

  Coverage:
    runs-on: ubuntu-latest
    timeout-minutes: 9
    services:
      postgres:
        image: postgres:18.4-alpine3.23
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: your_password
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready --health-interval 1s --health-timeout 0.5s --health-retries 30
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: ./.github/actions/setup
      - run: git rev-parse HEAD > git.sha
      - run: pnpm test:coverage:increased
        env:
          RECOVERAGE_CLOUD_TOKEN: ${{ secrets.RECOVERAGE_CLOUD_TOKEN }}

  BreakCheck:
    name: Break Check
    runs-on: ubuntu-latest
    timeout-minutes: 9
    services:
      postgres:
        image: postgres:18.4-alpine3.23
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: your_password
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready --health-interval 1s --health-timeout 0.5s --health-retries 30
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: ./.github/actions/setup
      - run: pnpm test:semver
